[project]
name = "testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "matplotlib>=3.11.1",
    "mlxtend>=0.25.0",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "spacy>=3.8.16",
    "sqlalchemy>=2.0.51",
    "torch>=2.14.0",
    "torchmetrics>=1.9.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]

[dependency-groups]
dev = [
    "debugpy>=1.8.22",
    "ipykernel>=7.3.0",
]
